### ISSUE TITLE
Separate public and private API with // MARK

### ISSUE THREAD

**Issue by AntonPalich** [badoo/swift-style-guide#12]
**Preferred:**

```swift
public class Foo {

// MARK: - Public

public var a: Int
public func doSomething() {}

// MARK: -  Private

private var b: Int
private var c: Float
private func doSomethingElse() {}
}
```

**Comment by BohdanOrlov** [comment]
I'm for separation, but sometimes it is much more convenient to keep private variables under the public method. 
Pros:
- a private variable stays as close as possible to its usage.
- it's much easier to refactor having related code together.

```swift
// MARK: - Public
public var isSaving: Bool 

public func save() {}
private var storage: Storage

// MARK: -  Private
private func trackEvent() {}
private var tracker: Tracker

```

**Comment by alexissan** [comment]
I don't think it's necessary to establish this kind of separation because we already have the visibility keyword to know if it is private or not. 

I prefer to separate by functionality and forget about visibility, for example: 

```swift
private var tracker: Tracker

// MARK: - Lifecycle
public func viewDidLoad()
public func viewDidAppear()
private func setupTableView()

// MARK: -  Hotpanel
private func trackEvent() {}
```

**Comment by radekcieciwa** [comment]
@BohdanOrlov It's a cool idea, but if we would follow that, I'ld suggest to mark sucha a corresponding code blocks with // Mark as well.

@alexissan +1 for Lifecycle mark 

And from me, as `clean code` states, there is proposed order of class elements, static variables, variables, functions ... Maybe we can reference there?

**Comment by AntonPalich** [comment]
Declined
