### ISSUE TITLE
Use 'me' instead of 'sSelf' for localised strong reference to self

### ISSUE THREAD

**Issue by shuaib** [badoo/swift-style-guide#13]
`guard let me = self else { return }`

instead of 

`guard let sSelf = self else { return }`

`me` is short, one word, easy to pronounce, and easy to type.
`sSelf`, is unnecessary camel case, difficult to pronounce, difficult to type, and has abbreviation.

Existing usage can easily be changed with find/replace.

**Comment by radekcieciwa** [comment]
I think you shouldn't vote on yourself :P 

I don't have a strong opinion on that one, but I'ld only add a question. 

Assuming that abbreviations are good (easy, short, speakable), are they intentfull - (will you understand the purpose of that variable 10 lines below)
sSelf - Strong Self
me - ??
 
For me either is good, cause I assume that block will be short enough to see guard statement.

**Comment by shuaib** [comment]
In this context, `me` will be easily understandable, because by convention it would mean strong self.

**Comment by BohdanOrlov** [comment]
`self` is the reserved word that has to be learned, we all learned it and get used to it, I don't feel like learning and especially explaining to newcomers the new word `me`. 

Yes, `sSelf` is cumbersome, but it requires no explanation.

**Comment by shuaib** [comment]
Learning new practices is the epitome of our profession. :)

Let's assume a hypothetical situation that there will be no newcomers in future. Will you like to adopt `me` instead of `sSelf` then? If 'yes', than it means it is a good practice and we should't worry about having to explain it. If 'no', than we should't adopt it even if we didn't have to explain it to newcomers.

**Comment by AntonPalich** [comment]
This repo is deprecated. If the issue is still relevant, please open it in [ios-guidelines](https://github.com/badoo/ios-guidelines)
