### ISSUE TITLE
Use "Protocol" suffix in protocol names

### ISSUE THREAD

**Issue by AntonPalich** [badoo/swift-style-guide#6]
**Preferred:**

```swift
protocol NetworkServiceProtocol {
}
```

**Not Preferred:**

```swift
protocol NetworkService {
}
```

**Comment by wiruzx** [comment]
Since we'll be referencing protocol name much more often than implementation name(only once), I'd consider making this experience nicer. But I don't like having `Impl` suffix either. 

Also there are cases, when we don't need suffixes, for example:

```
protocol Cache {}
class DiskCache: Cache {}
```

or

```
protocol Deletable {
    func delete()
}
```

**Comment by radekcieciwa** [comment]
I'ld like to suggest a change to this issue, or I can craete a new one? @AntonPalich ??

There is a fine talk wherre the guy analyzed the Foundation library naming. (I couldn't find it yet, I'll try later). But the main idea there is:

Protocols are named by adding Suffix:
- [...] able (when it contains certain behaviour or ability), e.g. Decodable
- [...] ing (uncommon, about certain action), e.g. DecimalConverting
- Type (quite popular - especially in our case - when you want to treat protocol as an object/type), PushNotificationManagerType

Classes, structs, enums are named as intented, e.g. PushNotificationManager. 

Pros:
- It's really intentfull (you know the intent of the developer)
- It's commonly used by Swift team and many 3rd party frameworks (e.g. JSON Parsers)

Really like the idea, I've been using it really long time.

**Comment by AntonPalich** [comment]
@radekcieciwa Can you create new proposal? We can suspend this issue for a while

**Comment by AntonPalich** [comment]
This repo is deprecated. If the issue is still relevant, please open it in [ios-guidelines](https://github.com/badoo/ios-guidelines)
