### ISSUE TITLE
Don’t use prefix in extensions to Swift types. Use prefix in extensions to Objective-C types only.

### ISSUE THREAD

**Issue by AntonPalich** [badoo/swift-style-guide#7]
**Preferred:**

```swift
extension String {
    func printFancyVersion { }
}
```

**Not preferred:**

```swift
extension String {
    func bma_printFancyVersion { }
}
```

**Comment by diegosanchezr** [comment]
Without a prefix, there's a higher risk of collisions, which would result in compiler error.

**Comment by AntonPalich** [comment]
@diegosanchezr If you have collisions may be you create a func or property that will do same things that other functions do? Compilation error would allow you to look into it.

**Comment by diegosanchezr** [comment]
Imagine you have such an extension. Then you add a new 3rd party library, or one of the ones you use gets updated. Then you have to fix the collision and refactor all callers. IMO, that should be avoided from the beginning.

**Comment by radekcieciwa** [comment]
@AntonPalich Can  you provide an example of this one. Probably the "google drive doc" will die soon, and here it will be the last point of knowledge on the topic. Though title don't says nothing to me :)

**Comment by AntonPalich** [comment]
This repo is deprecated. If the issue is still relevant, please open it in [ios-guidelines](https://github.com/badoo/ios-guidelines)
